namespace FizzCode.EtLast;

internal static class CustomColoredProperties
{
    internal static Dictionary<string, ColorCode> Map { get; } = new Dictionary<string, ColorCode>()
    {
        //["Module"] = ColorCode.Module,
        //["Plugin"] = ColorCode.Plugin,
        ["IoResult"] = ColorCode.Result,
        ["ProcessResult"] = ColorCode.Result,
        ["Caller"] = ColorCode.Process,
        ["Process"] = ColorCode.Process,
        ["ActiveProcess"] = ColorCode.Process,
        ["ProcessId"] = ColorCode.Process,
        ["ActiveProcessId"] = ColorCode.Process,
        ["Task"] = ColorCode.Task,
        ["ActiveTask"] = ColorCode.Task,
        ["TaskId"] = ColorCode.Task,
        ["ActiveTaskId"] = ColorCode.Task,
        ["Input"] = ColorCode.Process,
        ["Operation"] = ColorCode.Operation,
        ["Job"] = ColorCode.Job,
        ["Transaction"] = ColorCode.Transaction,
        ["ConnectionStringName"] = ColorCode.Location,
        ["TableName"] = ColorCode.Location,
        ["TableNames"] = ColorCode.Location,
        ["SchemaName"] = ColorCode.Location,
        ["SchemaNames"] = ColorCode.Location,
        ["SourceTableName"] = ColorCode.Location,
        ["TargetTableName"] = ColorCode.Location,
        ["FileName"] = ColorCode.Location,
        ["FilePath"] = ColorCode.Location,
        ["SourceFileName"] = ColorCode.Location,
        ["TargetFileName"] = ColorCode.Location,
        ["SourceFilePath"] = ColorCode.Location,
        ["TargetFilePath"] = ColorCode.Location,
        ["Folder"] = ColorCode.Location,
        ["Directory"] = ColorCode.Location,
        ["Path"] = ColorCode.Location,
        ["SourcePath"] = ColorCode.Location,
        ["TargetPath"] = ColorCode.Location,
        ["Url"] = ColorCode.Location,
        ["SourceUrl"] = ColorCode.Location,
        ["TargetUrl"] = ColorCode.Location,
        ["Container"] = ColorCode.Location,
        ["SourceContainer"] = ColorCode.Location,
        ["TargetContainer"] = ColorCode.Location,
        ["Pattern"] = ColorCode.Location,
        ["SourcePattern"] = ColorCode.Location,
        ["TargetPattern"] = ColorCode.Location,
    };
}
