name: dev-test

on:
  push:
    branches: [ "dev" ]
  pull_request:
    types: [opened, reopened]
    
jobs:
  build:
    runs-on: windows-latest

    env:
      Configuration: Release
      Version: ${{ vars.MAJORVERSION }}.${{ vars.MINORVERSION }}.${{ github.run_number }}.${{ vars.REVISION }}
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9
        #dotnet-quality: 'preview'
    
    - name: Restore
      run: dotnet restore FizzCode.EtLast.sln /p:Configuration=${{ env.Configuration }} --verbosity normal
    
    - name: Build
      run: dotnet build FizzCode.EtLast.sln --configuration ${{ env.Configuration }} --no-restore /p:Version=${{ env.Version }} --verbosity normal
    
    - name: Test
      run: dotnet test FizzCode.EtLast.sln --configuration ${{ env.Configuration }} --no-build --verbosity normal
