name: on-main-commit

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Extract Version
      if: ${{ github.ref_type == 'tag' }}
      env:
        TAG: ${{ github.ref_name }}
      run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8
        dotnet-quality: 'preview'
    
    - name: Restore
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore /p:Version=$VERSION
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
