name: on-main-commit

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Configuration: Release
      Version: ${{ vars.MAJORVERSION }}.${{ vars.MINORVERSION }}.${{ github.run_number }}.${{ vars.REVISION }}
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8
        dotnet-quality: 'preview'
    
    - name: Restore
      run: dotnet restore --configuration ${{ env.Configuration }}
    
    - name: Build
      run: dotnet build --configuration ${{ env.Configuration }} --no-restore /p:Version=${{ env.Version }}
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
